{{- if .Values.ingress.hosts -}}
{{- $fullName := .Values.service.name -}}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}

{{ if .Values.service.name }}
  {{- $fullName = .Values.service.name -}}
{{ end}}

apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: extensions/v1
{{- end }}
kind: Ingress
metadata:
  name: {{ .Values.service.name }}
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: nginx
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{ $hosts := splitList "," .Values.ingress.hosts -}}
    {{- range $hosts }}
    - host: {{ . | quote }}
      http:
        paths:
        - backend:
            service:
              name: {{  $fullName }}
              port:
                number: {{ $svcPort }}
          path: /
          pathType: Prefix
    {{- end }}
  {{- end }}
  