{{- $secrets := include "helpers.env-secrets" . -}}
{{- if gt (len $secrets) 0 -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.service.name }}-secrets
data:
  {{- include "helpers.env-secrets" . | indent 2 }}
{{- end -}}
